[build-system]
requires = ["setuptools>=46.1.0", "pybind11>=2.6"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-frontend = "pip"

[tool.pyright]
include = ["chdb"]
exclude = ["src", "contrib", "programs", "build", "buildlib", "dist", "venv", ".venv", ".vscode", ".git", "__pycache__", ".mypy_cache", ".pytest_cache"]

[project]
name = "chdb"
# Add other required fields here, such as:
version = "0.1.0"
description = "chDB is an in-process OLAP SQL Engine powered by ClickHouse"
authors = [{name = "auxten", email = "auxten@clickhouse.com"}]

[project.urls]
Homepage = "https://clickhouse.com/chdb"
Documentation = "https://clickhouse.com/docs/en/chdb"
Source = "https://github.com/chdb-io/chdb"
Download = "https://pypi.org/project/chdb/#files"
Twitter = "https://twitter.com/chdb_io"
