name: Pull-CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    env:
      PYTHON_VERSIONS: "3.11"

    runs-on: gh-64c
    steps:
      - name: Check for chdb directory
        run: |
          if [ ! -d "/home/ubuntu/pr_runner/chdb" ]; then
            echo "chdb directory does not exist. Checkout the repository."
            mkdir -p /home/ubuntu/pr_runner/
            git clone https://github.com/chdb-io/chdb.git /home/ubuntu/pr_runner/chdb
          fi

      - name: Cleanup and update chdb directory
        run: |
          cd /home/ubuntu/pr_runner/chdb
          git fetch origin || true
          git fetch origin +refs/heads/*:refs/remotes/origin/* +refs/pull/${{ github.event.pull_request.number }}/merge:refs/remotes/pull/${{ github.event.pull_request.number }}/merge || true
          git reset --hard origin/${{ github.head_ref }} || true
          git clean -fdx || true
          git checkout --progress --force refs/remotes/pull/${{ github.event.pull_request.number }}/merge || true
          git status -v || true
        continue-on-error: true

      - name: Code style check
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          pyenv local 3.11
          python3 -m pip install flake8
          cd chdb && python3 -m flake8
        working-directory: /home/ubuntu/pr_runner/chdb
